server:
  port: 8083

spring:
  application:
    name: api-gateway
  # Add Zipkin url. If we are using Spring Profiles we can change base-url into them, according to the environment that we have
  zipkin:
    base-url: http://localhost:9411
  # Setup Spring Could Gateway custom load balancer routes
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

# Eureka Client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # it is true by default
    register-with-eureka: true # it is true by default
